Repository excalidraw/excalidraw, pull requests merged in 2020-02, with the labels that each got.

#635 Reintroduce multi-point arrows and add migration for it
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  src/actions/actionDeleteSelected.tsx
  src/actions/actionFinalize.tsx
  src/actions/index.ts
  src/actions/manager.tsx
  src/actions/types.ts
  src/appState.ts
  src/element/bounds.ts
  src/element/collision.ts
  src/element/handlerRectangles.ts
  src/element/index.ts
  src/element/newElement.ts
  src/element/resizeTest.ts
  src/index.tsx
  src/math.ts
  src/renderer/renderElement.ts
  src/renderer/renderScene.ts
  src/scene/data.ts
  src/types.ts
  src/utils.ts
Labels: do not merge

#678 Load only valid excalidraw json when drag&drop
  src/scene/data.ts
Labels: do not merge

#685 Added Norwegian Bokmål
  src/i18n.ts
  src/locales/nb-no.json
Labels: translation

#642 Add encryption
  src/components/StoredScenesList.tsx
  src/index.tsx
  src/scene/data.ts
  src/scene/types.ts
Labels: do not merge

#701 Fix issues related to history
  src/actions/actionCanvas.tsx
  src/actions/actionDeleteSelected.tsx
  src/actions/actionFinalize.tsx
  src/actions/actionProperties.tsx
  src/actions/actionStyles.ts
  src/actions/actionZindex.tsx
  src/actions/manager.tsx
  src/actions/types.ts
  src/appState.ts
  src/components/ExportDialog.tsx
  src/element/sizeHelpers.ts
  src/history.ts
  src/index.tsx
  src/renderer/renderScene.ts
  src/scene/data.ts
  src/scene/export.ts
  src/scene/selection.ts
  src/types.ts
Labels: bug, do not merge, refactor

#655 Fast & Furious
  src/appState.ts
  src/clipboard.ts
  src/element/newElement.ts
  src/history.ts
  src/index.tsx
  src/renderer/renderElement.ts
  src/renderer/renderScene.ts
  src/scene/data.ts
  src/scene/export.ts
  src/scene/scrollbars.ts
  src/scene/types.ts
  src/styles.scss
  src/types.ts
Labels: do not merge
